#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitor true
# bspc config pointer_follows_monitor true # this one will be important later

bspc monitor eDP-1 -d I II III IV V VI VII VIII

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config remove_unplugged_monitor true
bspc config remove_disabled_monitors true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

startup &
